# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    container_name: wiki-db
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    networks:
      - wiki_network
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    container_name: wiki-adminer
    image: adminer:latest
    networks:
      - wiki_network
    logging:
      driver: "none"
    ports:
      - "3001:8080"

  wiki:
    container_name: wiki-app
    build:
      context: ../..
      dockerfile: dev/containers/Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - wiki_network
    volumes:
      - ../..:/wiki
      - /wiki/node_modules
      - /wiki/.git

volumes:
  db-data:

networks:
  wiki_network:
    driver: bridge
    external: true
